Repository Tanmay-tiwari-cyber/c-programs, pull requests merged in 2022-10, with the labels that each got.

#4 Create Program to Print English Alphabets
  Program to Print English Alphabets.c
Labels: accepted, hacktoberfest

#5 Add files via upload
  lab1a.c
Labels: hacktoberfest

#7 Added Code and CONTRIBUTION file
  CONTRIBUTION.md
  Palindrome.c
Labels: hacktoberfest

#10 created c program for checking armstrong numbers
  checkarmstrong.c
  transposematrix.c
Labels: hacktoberfest

#9 Create Armstrong Number.c
  Armstrong Number.c
  CONTRIBUTION.md
Labels: hacktoberfest

#8 Added round robin cpu scheduling
  roundrobin.c
Labels: hacktoberfest

#11 Using of function
  CONTRIBUTION.md
  main.cpp
Labels: hacktoberfest

#14 Password protected program
  password.c
Labels: hacktoberfest

#15 added some c programs
  Powerset.c
  Tower-of-hanoi.c
  check-Leapyear.c
  fibonacci-series.c
  stack-operations.c
Labels: hacktoberfest

#16 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: hacktoberfest

#13 check prime number code
  primeNmb.c
Labels: hacktoberfest

#17 passwordgenerator
  passwordgenrator.c
Labels: hacktoberfest

#19 Create binary_search.c
  binary_search.c
Labels: hacktoberfest

#20 prime.c
  prime.c
Labels: hacktoberfest

#21 Customer_Billing.c
  Customer_Billing.c
Labels: hacktoberfest

#23 guess_the_number.c
  guess_the_number.c
Labels: hacktoberfest

#22 Create palindrome.c
  palindrome.c
Labels: hacktoberfest

#25 Create facctorial.c
  facctorial.c
Labels: hacktoberfest

#24 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: hacktoberfest

#18 Queue.c
  Queue.c
Labels: hacktoberfest

#26 Added C Programs
  ArrayReverse.c
  ArraySort.c
  ArraySorting.c
  Binary to Hexadecimal Converter.c
  Bogo Sort.c
  CapSeriesOf2.c
  Decimal to Binary Converter.c
  Decimal to Hexadecimal Converter.c
  Decimal to Octal Converter.c
  FindMissingElement.c
  FirstNonRepeatingCharacter.c
  InsertionSort.c
  Largest_SmallestElementInArray.c
  Octal to Decimal Converter.c
  Octal to Hexadecimal Converter.c
  RemoveCharactersFromAStringExceptAlphabets.c
  Series(2+5+11+23).c
  Series(3+33+333+3333).c
  Series(7 10 8 11 9 ..).c
  SquareOfEachElementInAnArray.c
  SumOfElementsInAnArray.c
  SumOfIndNUM.c
  sample1.c
  squarePattern.c
Labels: hacktoberfest

#27 Bell Desgin with CG in C
  BELL.C
Labels: hacktoberfest

#28 adeed how to find roots of quad eqn
  roots quad.c
Labels: hacktoberfest

#29 Create singly linked list.c
  singly linked list.c
Labels: hacktoberfest

#34 Armstrong Number Program in C Language
  Armstrong.c
Labels: hacktoberfest

#33 Create ReaderWriter Problem
  ReaderWriter.c
Labels: hacktoberfest

#32 unbounded_kanpsack
  Unbounded_knapsack
Labels: hacktoberfest

#31 circular_queue in python
  Circular_queue in pyhton
Labels: hacktoberfest

#30 Krukshal.c++
  Krukshal
Labels: hacktoberfest

#35 Create Binarytodesimal.c
  Binarytodesimal.c
Labels: hacktoberfest

#36 Created Factorial program in C
  Factorial program in C
Labels: hacktoberfest

#40 Create problem.cpp
  problem.cpp
Labels: hacktoberfest

#37 Created Fibonacci Series in C
  Fibonacci Series in C
Labels: hacktoberfest

#42 Create prodg.c
  prodg.c
Labels: hacktoberfest

#50 Create HeapSort.c
  HeapSort.c
Labels: hacktoberfest

#49 Create Bucket_sort.c
  Bucket_sort.c
Labels: hacktoberfest

#46 bfs.c
  bfs.c
Labels: hacktoberfest

#43 Created star pattern program in C language
  Star pattern program
Labels: hacktoberfest

#44 Create code.c
  code.c
Labels: hacktoberfest

#55 Create bell1.c
  bell1.c
Labels: hacktoberfest, hacksquad

#56 Create sort.c
  Armstrong1.c
  sort.c
Labels: hacktoberfest, hacksquad

#59 counting_rooms graphs
  counting_rooms.cpp
Labels: hacktoberfest

#58 Create bfsanddfs.c
  punya/bfsanddfs.c
Labels: hacktoberfest

#54 added SJF scheduling algorithm
  Shortest_job_first.c
Labels: hacktoberfest

#60 Create fractional knapsack.c
  fractional knapsack.c
Labels: hacktoberfest

#64 hacksquad
  about_us.html
Labels: hacktoberfest, hacksquad

#65 hacksquad
  chef_food.html
  food_booking.html
Labels: hacktoberfest, hacksquad

#66 Add files via upload
  index.html
Labels: hacktoberfest, hacksquad

#67 Application Problems using C Programming
  Airline_set_reservation.c
  bank_management.c
Labels: hacktoberfest

#68 HackerRank Problem Sollutions
  candy_wending_machine.c
  hackerrank_car_parking.c
Labels: hacktoberfest

#71 Create cal.c
  cal.c
Labels: hacktoberfest, hacksquad

#72 Create student.c
  student.c
Labels: hacktoberfest, hacksquad

#73 Create calendar.c
  calendar.c
Labels: hacktoberfest, hacksquad

#74 Create phonebook.c
  phonebook.c
Labels: hacktoberfest, hacksquad

#75 Create unit.c
  unit.c
Labels: hacktoberfest, hacksquad

#70 Create bubble_sort.c
  bubble_sort.c
Labels: hacktoberfest

#81 find roots of a quadratic equation
  find_roots_of_quadratic_equation.c
Labels: hacktoberfest

#83 Create timesort algorithm
  timesort algorithm
Labels: hacktoberfest

#84 Create Simple_queue.c
  Simple_queue.c
Labels: hacktoberfest

#86 Add files via upload
  sum_of_digits_1to10.c
Labels: hacktoberfest
